# Where things are
source              : .
destination         : ./_site
#collections_dir    : .        # defining a route crashes exporting
plugins_dir         : _plugins # takes an array of strings and loads plugins in that order
layouts_dir         : _layouts
data_dir            : _data
includes_dir        : _includes
sass:
  sass_dir: _sass
collections:
  es:
    output          : true
    permalink       : /:collection/:path
  en:
    output          : true
    permalink       : /:collection/:path

# Handling Reading
safe                : false
include             : [".htaccess"]
exclude:
-  "Gemfile"
-  "Gemfile.lock"
-  "README.md"
-  "*/ext/*"
keep_files          : [".git", ".svn"]
encoding            : "UTF-8"
markdown_ext        : "markdown,mkdown,mkdn,mkd,md"
strict_front_matter : true

# Filtering Content
show_drafts         : false
limit_posts         : 0
future              : false
unpublished         : false

# Plugins
whitelist           : []
plugins             : []

# Conversion
markdown            : kramdown
highlighter         : rouge
lsi                 : false
excerpt_separator   : "\n\n"
incremental         : false

# Serving
detach              : false
port                : 4000
host                : 127.0.0.1
baseurl             : "" # does not include hostname
show_dir_listing    : false

# Outputting
permalink           : pretty
paginate_path       : /page:num
#timezone           : null #requieres a plugin for succesful compiling

#quiet               : false
#verbose             : false
#defaults            : []

#liquid:
# error_mode        : warn
#  strict_filters   : false
#  strict_variables : false

# Markdown Processors
#kramdown:
# auto_ids          : true
# entity_output     : as_char
# toc_levels        : 1,2,3,4,5,6
# smart_quotes      : lsquo,rsquo,ldquo,rdquo
# input             : GFM
# hard_wrap         : false
# footnote_nr       : 1
# show_warnings     : false
  